Repository insightsengineering/hermes, pull requests merged in 2021-11, with the labels that each got.

#152 Add gitleaks
  .github/workflows/gitleaks.yaml
Labels: devops

#153 add issue templates codeowners@main
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: automation

#156 Add bioccheck action
  .github/workflows/check.yaml
Labels: automation

#157 Relevant updates from BioConductor master branch.
  .lintr
  DESCRIPTION
  NEWS.md
  R/pca_cor_samplevar.R
  README.Rmd
  README.md
  inst/WORDLIST
  tests/testthat/_snaps/calc_cor/autoplot-for-hermesdatacor-with-custom-options.svg
  tests/testthat/_snaps/calc_cor/autoplot-for-hermesdatacor-with-default-options.svg
  tests/testthat/_snaps/differential/autoplot-for-hermesdatadiffexpr-with-custom-options.svg
  tests/testthat/test-connections.R
  tests/testthat/test-pca_cor_samplevar.R
  vignettes/introduction.Rmd
Labels: blocked
